//! `spark-abi`: `#[repr(C)]` bindings to the sparkpipe C ABI.
//!
//! Everything in this crate is auto-generated by bindgen from the C headers in
//! the sibling `sparkpipe` repo (`include/sparkpipe/*.h`,
//! `model-families/glm52/include`). Hand-written code does not belong here;
//! safe wrappers live in `spark-sys`.
//!
//! # ABI discipline
//!
//! The C side versions every struct with `abi_version` + `descriptor_bytes`
//! fields checked at every entry point. Callers must initialize these fields
//! from the generated `SPARK_*_ABI_VERSION` / `SPARK_*_DESCRIPTOR_BYTES`
//! constants before handing structs to C. `spark-sys` enforces this in its
//! constructors; direct users of this crate are on their own.

#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// C-computed struct layouts (`sizeof`/`_Alignof`) for every ABI struct that
/// crosses the FFI boundary. Generated at build time by compiling and running
/// a probe against the real C headers — these are the ground truth the
/// `layout_gate` test pins the bindgen-generated types against.
pub mod layout {
    #![allow(clippy::all)]
    include!(concat!(env!("OUT_DIR"), "/layout.rs"));
}
